Algoritmo AHORROS
	DEFINIR COUTA,MES,AHORRO_TOTAL Como Real
	MES=1
	AHORRO_TOTAL=0
	Mientras MES<=12 Hacer
		Escribir "DIGITA EL VALOR DEL AHORRO DEL MES " MES ": "
		LEER COUTA
		AHORRO_TOTAL=AHORRO_TOTAL+COUTA
		Imprimir "EL TOTAL AHORRADO MES A MES ES: $ " AHORRO_TOTAL
		MES=MES+1
	FinMientras
	Imprimir "EL TOTAL AHORRADO EN EL AÑOS ES: $ " AHORRO_TOTAL
FinAlgoritmo
