Algoritmo COMPAÑIA
	NOM=TEXTO
	ID=NUMERO
	NHT=NUMERO
	VHT=NUMERO
	SALA=NUMERO
	Escribir ("INGRESE EL NOMBRE DEL EMPLEADO")
	LEER NOM
	Escribir ("INGRESE NUMERO DE IDENFICACION DEL EMPLEADO")
	LEER ID
	Escribir ("INGRESE NUMERO DE HORAS LABORADAS")
	LEER NHT
	Escribir ("INGRESE VALOR DE LA HORA")
	LEER VHT
	SALA=NHT*VHT
	Imprimir "EL NOMBRE DEL EMPLEADO ES ", NOM, " Y SU SALARIO NETO ES ", SALA
FinAlgoritmo
